:tada: NEW: CSR admin ui (entities metadata)
remult/remult pull request #584
Opened 2024-12-09 21:22 UTC by jycouet

2024-12-09 21:23 UTC, jycouet commented on projects/core/server/remult-api-server.ts
> +          }
It's working, but I'm sure you can find a better way 😎

2024-12-09 23:08 UTC, jycouet commented
To add tomorrow : don't return anything when the admin flag is not allowed!

2024-12-16 13:18 UTC, jycouet commented on projects/core/server/remult-api-server.ts
> +          }
solved :)

2024-12-25 17:51 UTC, noam-honig requested changes

2024-12-25 17:51 UTC, noam-honig commented on projects/core/server/remult-api-server.ts
> +        r.route(this.options.rootPath + '/admin/entities-metadata').get(
I would change that to be `__entities-metadata` to not accidently conflict with an entity that is named like `entities-metadata`

2024-12-25 17:51 UTC, noam-honig commented on projects/core/server/remult-api-server.ts
> +        r.route(this.options.rootPath + '/admin/entities-metadata').get(
@jycouet did you get a chance to exemine this concern?

2024-12-25 18:32 UTC, jycouet commented on projects/core/server/remult-api-server.ts
> +        r.route(this.options.rootPath + '/admin/entities-metadata').get(
Yes 👍

2024-12-30 08:00 UTC, noam-honig commented on projects/remult-admin/src/stores/GodStore.ts
> +    remult.initUser().then(() => {
@jycouet I've added this code so that remult will be aware of the current user - it is used as part of the id of a live query. can you versify that you're ok with that?

2025-01-01 07:08 UTC, merged